### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by oujieww** [hasanirtiza/Pedestron#1] opened 2020-03-25 09:48 UTC
when runing for test, the code needs val_gt.json file, so i change the path in test_city_person.py to "val_gt_for mmdetection.json". and get following problem. 

 File "tools/test_city_person.py", line 225, in <module>
    main()
  File "tools/test_city_person.py", line 219, in main
    MRs = validate('Pedestron/datasets/CityPersons/val_gt_for_mmdetction.json', args.out)
  File "Pedestron/tools/cityPerson/eval_demo.py", line 10, in validate
    cocoDt = cocoGt.loadRes(dt_path)
  File "Pedestron/tools/cityPerson/coco.py", line 313, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range

**Comment by hasanirtiza** [comment] 2020-03-25 11:52
Did you use one of the pre-trained models provided by us ? Usually this error comes when your model is unable to make any predictions on test image. Since the error log shows the problem in the detection file not the ground-truth. Additionally, if you can simply run the demo using one or two images using your model (in-case you are using your own model).

**Comment by hasanirtiza** [comment] 2020-03-25 15:07
Furthermore, we have resolved paths and added val_gt.json along with fixing of some minor bugs. We have tested our provided pre-trained model (on this repo for CityPersons) for demo and test_cityperson.py and we have managed to reproduce the numbers. Training of new model should also be fine, it should work on your side as well. I would suggest you to clone and update your local repo.

**Comment by AyeshaNirma** [comment] 2020-03-27 09:07
I can now run the test_cityperson.py without hiccup on my machine

**Comment by oujieww** [comment] 2020-03-30 19:06
thank u so much @hasanirtiza !!!

**Comment by oujieww** [comment] 2020-03-30 19:15
@hasanirtiza could u share me how to choose setting for retinanet.py for cityperson?

**Comment by oujieww** [comment] 2020-03-30 19:15
@hasanirtiza could u share me how to choose setting for retinanet.py for cityperson? thank you

**Comment by hasanirtiza** [comment] 2020-03-30 19:22
@oujieww I suggest you to create a new issue with [feature request] (close this one). I believe we can provide support for RetinaNet as well.

**Comment by oujieww** [comment] 2020-03-31 14:35
@hasanirtiza thank you!

**Closed as completed** 2020-03-31 14:36 UTC
